// Generated by LiveScript 1.3.1
(function(){
  var worked, ready, fresh, enableAllButs, setUnread, start, action;
  $(function(){
    fresh();
    start();
    return document.getElementById("test").onmouseout = function(){
      if (event.offsetX < -1 || event.offsetX > 140 || event.offsetY > 279 || event.offsetY < -1) {
        fresh();
        start();
      }
    };
  });
  worked = [];
  ready = [];
  fresh = function(){
    enableAllButs();
    setUnread();
  };
  enableAllButs = function(){
    var i, buts, i$, len$, but;
    i = 0;
    buts = $(".control-ring-container li");
    for (i$ = 0, len$ = buts.length; i$ < len$; ++i$) {
      but = buts[i$];
      $(but).addClass("init");
      worked[i] = 'free';
      ready[i++] = 'yes';
    }
  };
  setUnread = function(){
    var unreads, i$, len$, unread;
    unreads = $(".control-ring-container span");
    for (i$ = 0, len$ = unreads.length; i$ < len$; ++i$) {
      unread = unreads[i$];
      $(unread).css("visibility", "hidden").html("...");
    }
  };
  start = function(){
    var range, buts, i$, len$, but;
    range = [0, 1, 2, 3, 4];
    buts = $(".control-ring-container li");
    for (i$ = 0, len$ = buts.length; i$ < len$; ++i$) {
      but = buts[i$];
      but.onclick = action;
    }
  };
  action = function(){
    var range, buts, i$, len$, i, p, XMLhttp;
    range = [0, 1, 2, 3, 4];
    buts = $(".control-ring-container li");
    for (i$ = 0, len$ = range.length; i$ < len$; ++i$) {
      i = range[i$];
      if (this === buts[i]) {
        p = i;
      }
    }
    if (worked[p] === 'work' || ready[p] === 'no') {
      return;
    }
    worked[p] = 'work';
    for (i$ = 0, len$ = range.length; i$ < len$; ++i$) {
      i = range[i$];
      ready[i] = 'no';
      if (i != p) {
        $(buts[i]).removeClass("init").addClass("disabled");
      }
    }
    XMLhttp = new XMLHttpRequest();
    XMLhttp.open("GET", "/", true);
    XMLhttp.send();
    XMLhttp.onreadystatechange = function(){
      var i$, ref$, len$, i;
      if (XMLhttp.readyState === 4 && XMLhttp.status === 200) {
        $(buts[p]).find("span").html(XMLhttp.responseText);
        $(buts[p]).removeClass("init").addClass["disabled"];
        for (i$ = 0, len$ = (ref$ = range).length; i$ < len$; ++i$) {
          i = ref$[i$];
          if (worked[i] === 'free') {
            ready[i] = 'yes';
          }
        }
        for (i$ = 0, len$ = (ref$ = range).length; i$ < len$; ++i$) {
          i = ref$[i$];
          if (ready[i] === 'yes') {
            $(buts[i]).removeClass("disabled").addClass("init");
          }
        }
        for (i$ = 0, len$ = (ref$ = range).length; i$ < len$; ++i$) {
          i = ref$[i$];
          if (worked[i] === 'free') {
            return;
          }
        }
        $(".info").addClass("init");
        $(".info".onclick = function(){
          var sum, i$, ref$, len$, i;
          sum = 0;
          for (i$ = 0, len$ = (ref$ = range).length; i$ < len$; ++i$) {
            i = ref$[i$];
            sum += parseInt($(buts[i]).find("span").html());
          }
          $(".info ul").html(sum.toString());
        });
      }
    };
    $(buts[p]).find("span").css("visibility", "visible");
  };
}).call(this);
